# fgn/commands/guide/guide_config.yml
defaults:
  template: guide_template.txt
  example: guide_example.txt
  system_prompt: guide_system_prompt.txt
  history_path: guide_history.txt
  model: gpt-3.5-turbo
  auto_clear: false
  verbose: false
  auto_summarize: int = 4