# fgn/commands/shell/shell_config.yml
defaults:
  template: shell_template.txt
  example: shell_example.txt
  system_prompt: shell_system_prompt.txt
  history_path: shell_history.txt
  model: gpt-3.5-turbo
  auto_clear: false
  verbose: false
  auto_summarize: int = 4