# fgn/commands/nano/nano_config.yml
defaults:
  template: nano_template.txt
  example: nano_example.txt
  system_prompt: nano_system_prompt.txt
  history_path: nano_history.txt
  model: gpt-3.5-turbo
  auto_clear: false
  verbose: false
  auto_summarize: int = 4