fgn -m4 -e blackboard.md  -o "chapter-01.md" blog "Introduction"
fgn -m4 -e blackboard.md  -i "chapter-01.md" -o "chapter-02.md" blog "Understanding the Basics"
fgn -m4 -e blackboard.md  -i "chapter-02.md" -o "chapter-03.md" blog "Setting Up Your Environment"
fgn -m4 -e blackboard.md  -i "chapter-03.md" -o "chapter-04.md" blog "Planning Your Project"
fgn -m4 -e blackboard.md  -i "chapter-04.md" -o "chapter-05.md" blog "Building Your First App"
fgn -m4 -e blackboard.md  -i "chapter-05.md" -o "chapter-06.md" blog "Testing Your Application"
fgn -m4 -e blackboard.md  -i "chapter-06.md" -o "chapter-07.md" blog "Deploying Your App"
fgn -m4 -e blackboard.md  -i "chapter-07.md" -o "chapter-08.md" blog "Understanding Advanced Concepts"
fgn -m4 -e blackboard.md  -i "chapter-08.md" -o "chapter-09.md" blog "Working with Databases"
fgn -m4 -e blackboard.md  -i "chapter-09.md" -o "chapter-10.md" blog "Integrating Third-Party Services"
fgn -m4 -e blackboard.md  -i "chapter-10.md" -o "chapter-11.md" blog "Securing Your Application"
fgn -m4 -e blackboard.md  -i "chapter-11.md" -o "chapter-12.md" blog "Optimizing Your Application"
fgn -m4 -e blackboard.md  -i "chapter-12.md" -o "chapter-13.md" blog "Scaling Your Application"
fgn -m4 -e blackboard.md  -i "chapter-13.md" -o "chapter-14.md" blog "Troubleshooting and Debugging"
fgn -m4 -e blackboard.md  -i "chapter-14.md" -o "chapter-15.md" blog "Automating Deployment"
fgn -m4 -e blackboard.md  -i "chapter-15.md" -o "chapter-16.md" blog "Exploring New Features"
fgn -m4 -e blackboard.md  -i "chapter-16.md" -o "chapter-17.md" blog "Keeping Your Skills Up to Date"
fgn -m4 -e blackboard.md  -i "chapter-17.md" -o "chapter-18.md" blog "Developing a Career in Software Development"
fgn -m4 -e blackboard.md  -i "chapter-18.md" -o "chapter-19.md" blog "Conclusion and Final Thoughts"
fgn -m4 -e blackboard.md  -i "chapter-19.md" -o "chapter-20.md" nano "Extra Nuggets of Wisdom"
```