fgn -e blackboard.md -o "chapter01-introduction.md" blog "Chapter 1: Introduction to Chat Function and DDD"
fgn -e blackboard.md -i "chapter01-introduction.md" -o "chapter02-setting-up.md" howto "Chapter 2: Setting Up Your Development Environment"
fgn -e blackboard.md -i "chapter02-setting-up.md" -o "chapter03-basic-usage.md" howto "Chapter 3: Basic Usage of the Chat Function"
fgn -e blackboard.md -i "chapter03-basic-usage.md" -o "chapter04-building-custom-function.md" guide "Chapter 4: Building a Custom Function with Funcs Parameter"
fgn -e blackboard.md -i "chapter04-building-custom-function.md" -o "chapter05-error-handling.md" howto "Chapter 5: Error Handling and Retries"
fgn -e blackboard.md -i "chapter05-error-handling.md" -o "chapter06-integrating-services.md" blog "Chapter 6: Integrating with Other Services"
fgn -e blackboard.md -i "chapter06-integrating-services.md" -o "chapter07-testing.md" guide "Chapter 7: Testing the Chat Function"
fgn -e blackboard.md -i "chapter07-testing.md" -o "chapter08-building-chatbot.md" howto "Chapter 8: Creating a Chatbot Using DDD"
fgn -e blackboard.md -i "chapter08-building-chatbot.md" -o "chapter09-advanced-techniques.md" blog "Chapter 9: Advanced Techniques with Chat Function"
fgn -e blackboard.md -i "chapter09-advanced-techniques.md" -o "chapter10-frontend-integration.md" howto "Chapter 10: Using Chat Function with Frontend Frameworks"
fgn -e blackboard.md -i "chapter10-frontend-integration.md" -o "chapter11-deployment.md" guide "Chapter 11: Deploying Your Chat Application"
fgn -e blackboard.md -i "chapter11-deployment.md" -o "chapter12-performance-tuning.md" blog "Chapter 12: Performance Tuning and Optimization"
fgn -e blackboard.md -i "chapter12-performance-tuning.md" -o "chapter13-building-framework.md" howto "Chapter 13: Building a Code Generation Framework"
fgn -e blackboard.md -i "chapter13-building-framework.md" -o "chapter14-security-compliance.md" guide "Chapter 14: Security and Compliance"
fgn -e blackboard.md -i "chapter14-security-compliance.md" -o "chapter15-monitoring-analytics.md" blog "Chapter 15: Monitoring and Analytics"
fgn -e blackboard.md -i "chapter15-monitoring-analytics.md" -o "chapter16-internationalization.md" howto "Chapter 16: Internationalization and Localization"
fgn -e blackboard.md -i "chapter16-internationalization.md" -o "chapter17-plugins-extensions.md" guide "Chapter 17: Creating Plugins and Extensions"
fgn -e blackboard.md -i "chapter17-plugins-extensions.md" -o "chapter18-contributing-oss.md" blog "Chapter 18: Contributing to Open Source"
fgn -e blackboard.md -i "chapter18-contributing-oss.md" -o "chapter19-future-trends.md" blog "Chapter 19: Future Trends and Technologies"
fgn -e blackboard.md -i "chapter19-future-trends.md" -o "chapter20-conclusion-resources.md" blog "Chapter 20: Conclusion and Resources"
```