fgn -i blackboard.md -o "weighted-graphs.py" code "Creating Accurate Weighted Graphs for Code Components"
fgn -i blackboard.md -e "weighted-graphs.py" -o "train-knowledge-extraction.py" code "Training a Knowledge Extraction Model for Estimating Code Distances"
fgn -i blackboard.md -e "train-knowledge-extraction.py" -o "enhance-pathfinding.py" code "Enhancing Multi-Goal Path Finding with PKE-RRT Algorithm"
fgn -i blackboard.md -e "enhance-pathfinding.py" -o "optimize-code-generation.py" code "Optimizing Code Generation Workflow with Chain-of-Thought Prompting"
fgn -i blackboard.md -e "optimize-code-generation.py" -o "versatile-code-generation.py" code "Achieving Versatile Code Generation with Vanilla CodeCoT"
fgn -i blackboard.md -e "versatile-code-generation.py" -o "iterative-self-examination.py" code "Implementing Iterative Self-Examination with Self-exam CodeCoT"
fgn -i blackboard.md -e "iterative-self-examination.py" -o "llm-adaptation.py" code "Improving Large Language Model Adaptation with Few-Shot Learning"
fgn -i blackboard.md -e "llm-adaptation.py" -o "enhanced-mgpf-codening.py" code "Enhancing Multi-Goal Path Finding with Dynamic Graph Heuristics"
fgn -i blackboard.md -e "enhanced-mgpf-codening.py" -o "evaluate-codecot.py" code "Evaluating CodeCoT Techniques Performance on LLM Variants"
fgn -i blackboard.md -e "evaluate-codecot.py" -o "enhance-llm-generalization.py" code "Enhancing Large Language Model Generalization with CoT Approaches"
fgn -i blackboard.md -e "enhance-llm-generalization.py" -o "llm-reasoning-cot.py" code "Empowering Large Language Model Reasoning with Chain-of-Thought Prompting"
fgn -i blackboard.md -e "llm-reasoning-cot.py" -o "assess-pke-rrt.py" code "Assessing PKE-RRT Algorithm Efficiency for Multi-Goal Path Finding"
fgn -i blackboard.md -e "assess-pke-rrt.py" -o "llm-adaptation-tasks.py" code "Fine-tuning Large Language Models for Specific Coding Tasks with CodeCoT"
fgn -i blackboard.md -e "llm-adaptation-tasks.py" -o "refine-code-generation.py" code "Refining Code Generation Accuracy with CoT Strategies"
fgn -i blackboard.md -e "refine-code-generation.py" -o "dynamic-graph-mgpf.py" code "Optimizing Multi-Goal Path Finding with Predicted Graph Weights"
fgn -i blackboard.md -e "dynamic-graph-mgpf.py" -o "cot-enhanced-performance.py" code "Enhancing Transformer-based Code Generation with Chain-of-Thought Techniques"
fgn -i blackboard.md -e "cot-enhanced-performance.py" -o "evaluate-llm-adaptation.py" code "Evaluating Large Language Model Adaptation Metrics with CodeCoT"
fgn -i blackboard.md -e "evaluate-llm-adaptation.py" -o "test-pke-rrt.py" code "Testing PKE-RRT Algorithm Performance in Complex Multi-Goal Path Finding Scenarios"
fgn -i blackboard.md -e "test-pke-rrt.py" -o "multi-task-learning.py" code "Exploring Multi-Task Learning Effectiveness with PKE Model"
fgn -i blackboard.md -e "multi-task-learning.py" -o "cot-empact.py" nano "Evaluating the Impact of Chain-of-Thought Techniques on Large Language Model Tasks"