# fgn/commands/feedback/feedback_config.yml
defaults:
  template: feedback_template.txt
  example: feedback_example.txt
  system_prompt: feedback_system_prompt.txt
  history_path: feedback_history.txt
  model: gpt-3.5-turbo
  auto_clear: false
  verbose: false
  auto_summarize: int = 4