# fgn/commands/dsl/dsl_config.yml
defaults:
  template: dsl_template.txt
  example: dsl_example.txt
  system_prompt: dsl_system_prompt.txt
  history_path: dsl_history.txt
  model: gpt-3.5-turbo
  auto_clear: false
  verbose: false
  auto_summarize: int = 4