fgn -m2 -a -i blackboard.md -o "Chapter02.md" code  " The Pragmatic Philosophy"
fgn -m2 -a -i blackboard.md -e "Chapter02.md" -o "Chapter03.md" code  "Pragmatic Starter Kit CLI DDD and code  Generation"
fgn -m2 -a -i blackboard.md -e "Chapter03.md" -o "Chapter04.md" code  "Pragmatic Starter Kit CLI Automated Testing with Pytest"
fgn -m2 -a -i blackboard.md -e "Chapter04.md" -o "Chapter05.md" code  "Pragmatic Starter Kit CLI Docker Compose for Environment Management"
fgn -m2 -a -i blackboard.md -e "Chapter05.md" -o "Chapter06.md" code  "Pragmatic Starter Kit CLI Continuous Integration with Git Actions"
fgn -m2 -a -i blackboard.md -e "Chapter06.md" -o "Chapter07.md" code  "Pragmatic Starter Kit CLI Refinement and Iteration in code  Generation"
fgn -m2 -a -i blackboard.md -e "Chapter07.md" -o "Chapter08.md" code  "Pragmatic Starter Kit CLI Version Control Strategies"
fgn -m2 -a -i blackboard.md -e "Chapter08.md" -o "Chapter09.md" code  "Pragmatic Starter Kit CLI Building the Pragmatic Starter Kit"
fgn -m2 -a -i blackboard.md -e "Chapter09.md" -o "Chapter10.md" code  "Pragmatic Starter Kit CLI Regression Testing and Full Automation"
fgn -m2 -a -i blackboard.md -e "Chapter10.md" -o "Chapter11.md" code  "Pragmatic Starter Kit CLI Monitoring and Performance Optimization"
fgn -m2 -a -i blackboard.md -e "Chapter11.md" -o "Chapter12.md" code  "Pragmatic Starter Kit CLI Documentation and Community Engagement"
fgn -m2 -a -i blackboard.md -e "Chapter12.md" -o "Chapter13.md" code  "Pragmatic Starter Kit CLI Security and Compliance"
fgn -m2 -a -i blackboard.md -e "Chapter13.md" -o "Chapter14.md" code  "Pragmatic Starter Kit CLI Deployment and Scalability"
fgn -m2 -a -i blackboard.md -e "Chapter14.md" -o "Chapter15.md" code  "Pragmatic Starter Kit CLI Debugging and Troubleshooting"
fgn -m2 -a -i blackboard.md -e "Chapter15.md" -o "Chapter16.md" code  "Pragmatic Starter Kit CLI Customizing the Pragmatic Starter Kit"
fgn -m2 -a -i blackboard.md -e "Chapter16.md" -o "Chapter17.md" code  "Pragmatic Starter Kit CLI Real-world Case Studies"
fgn -m2 -a -i blackboard.md -e "Chapter17.md" -o "Chapter18.md" code  "Pragmatic Starter Kit CLI Future Directions and Evolution"
fgn -m2 -a -i blackboard.md -e "Chapter18.md" -o "Chapter19.md" code  "Pragmatic Starter Kit CLI Contributing to the Project"
fgn -m2 -a -i blackboard.md -e "Chapter19.md" -o "Chapter20.md" code  "Pragmatic Starter Kit CLI Conclusion: Building a Pragmatic Future"
fgn -m2 -a -i blackboard.md -e "Chapter01.md" -o "Chapter02.md" code  " The Pragmatic Philosophy"
fgn -m2 -a -i blackboard.md -e "Chapter02.md" -o "Chapter03.md" code  "Pragmatic Starter Kit CLI DDD and code  Generation"
fgn -m2 -a -i blackboard.md -e "Chapter03.md" -o "Chapter04.md" code  "Pragmatic Starter Kit CLI Automated Testing with Pytest"
fgn -m2 -a -i blackboard.md -e "Chapter04.md" -o "Chapter05.md" code  "Pragmatic Starter Kit CLI Docker Compose for Environment Management"
fgn -m2 -a -i blackboard.md -e "Chapter05.md" -o "Chapter06.md" code  "Pragmatic Starter Kit CLI Continuous Integration with Git Actions"
fgn -m2 -a -i blackboard.md -e "Chapter06.md" -o "Chapter07.md" code  "Pragmatic Starter Kit CLI Refinement and Iteration in code  Generation"
fgn -m2 -a -i blackboard.md -e "Chapter07.md" -o "Chapter08.md" code  "Pragmatic Starter Kit CLI Version Control Strategies"
fgn -m2 -a -i blackboard.md -e "Chapter08.md" -o "Chapter09.md" code  "Pragmatic Starter Kit CLI Building the Pragmatic Starter Kit"
fgn -m2 -a -i blackboard.md -e "Chapter09.md" -o "Chapter10.md" code  "Pragmatic Starter Kit CLI Regression Testing and Full Automation"
fgn -m2 -a -i blackboard.md -e "Chapter10.md" -o "Chapter11.md" code  "Pragmatic Starter Kit CLI Monitoring and Performance Optimization"
fgn -m2 -a -i blackboard.md -e "Chapter11.md" -o "Chapter12.md" code  "Pragmatic Starter Kit CLI Documentation and Community Engagement"
fgn -m2 -a -i blackboard.md -e "Chapter12.md" -o "Chapter13.md" code  "Pragmatic Starter Kit CLI Security and Compliance"
fgn -m2 -a -i blackboard.md -e "Chapter13.md" -o "Chapter14.md" code  "Pragmatic Starter Kit CLI Deployment and Scalability"
fgn -m2 -a -i blackboard.md -e "Chapter14.md" -o "Chapter15.md" code  "Pragmatic Starter Kit CLI Debugging and Troubleshooting"
fgn -m2 -a -i blackboard.md -e "Chapter15.md" -o "Chapter16.md" code  "Pragmatic Starter Kit CLI Customizing the Pragmatic Starter Kit"
fgn -m2 -a -i blackboard.md -e "Chapter16.md" -o "Chapter17.md" code  "Pragmatic Starter Kit CLI Real-world Case Studies"
fgn -m2 -a -i blackboard.md -e "Chapter17.md" -o "Chapter18.md" code  "Pragmatic Starter Kit CLI Future Directions and Evolution"
fgn -m2 -a -i blackboard.md -e "Chapter18.md" -o "Chapter19.md" code  "Pragmatic Starter Kit CLI Contributing to the Project"
fgn -m2 -a -i blackboard.md -e "Chapter19.md" -o "Chapter20.md" code  "Pragmatic Starter Kit CLI Conclusion: Building a Pragmatic Future"
fgn -m2 -a -i blackboard.md -e "Chapter01.md" -o "Chapter02.md" code  " The Pragmatic Philosophy"
fgn -m2 -a -i blackboard.md -e "Chapter02.md" -o "Chapter03.md" code  "Pragmatic Starter Kit CLI DDD and code  Generation"
fgn -m2 -a -i blackboard.md -e "Chapter03.md" -o "Chapter04.md" code  "Pragmatic Starter Kit CLI Automated Testing with Pytest"
fgn -m2 -a -i blackboard.md -e "Chapter04.md" -o "Chapter05.md" code  "Pragmatic Starter Kit CLI Docker Compose for Environment Management"
fgn -m2 -a -i blackboard.md -e "Chapter05.md" -o "Chapter06.md" code  "Pragmatic Starter Kit CLI Continuous Integration with Git Actions"
fgn -m2 -a -i blackboard.md -e "Chapter06.md" -o "Chapter07.md" code  "Pragmatic Starter Kit CLI Refinement and Iteration in code  Generation"
fgn -m2 -a -i blackboard.md -e "Chapter07.md" -o "Chapter08.md" code  "Pragmatic Starter Kit CLI Version Control Strategies"
fgn -m2 -a -i blackboard.md -e "Chapter08.md" -o "Chapter09.md" code  "Pragmatic Starter Kit CLI Building the Pragmatic Starter Kit"
fgn -m2 -a -i blackboard.md -e "Chapter09.md" -o "Chapter10.md" code  "Pragmatic Starter Kit CLI Regression Testing and Full Automation"
fgn -m2 -a -i blackboard.md -e "Chapter10.md" -o "Chapter11.md" code  "Pragmatic Starter Kit CLI Monitoring and Performance Optimization"
fgn -m2 -a -i blackboard.md -e "Chapter11.md" -o "Chapter12.md" code  "Pragmatic Starter Kit CLI Documentation and Community Engagement"
fgn -m2 -a -i blackboard.md -e "Chapter12.md" -o "Chapter13.md" code  "Pragmatic Starter Kit CLI Security and Compliance"
fgn -m2 -a -i blackboard.md -e "Chapter13.md" -o "Chapter14.md" code  "Pragmatic Starter Kit CLI Deployment and Scalability"
fgn -m2 -a -i blackboard.md -e "Chapter14.md" -o "Chapter15.md" code  "Pragmatic Starter Kit CLI Debugging and Troubleshooting"
fgn -m2 -a -i blackboard.md -e "Chapter15.md" -o "Chapter16.md" code  "Pragmatic Starter Kit CLI Customizing the Pragmatic Starter Kit"
fgn -m2 -a -i blackboard.md -e "Chapter16.md" -o "Chapter17.md" code  "Pragmatic Starter Kit CLI Real-world Case Studies"
fgn -m2 -a -i blackboard.md -e "Chapter17.md" -o "Chapter18.md" code  "Pragmatic Starter Kit CLI Future Directions and Evolution"
fgn -m2 -a -i blackboard.md -e "Chapter18.md" -o "Chapter19.md" code  "Pragmatic Starter Kit CLI Contributing to the Project"
fgn -m2 -a -i blackboard.md -e "Chapter19.md" -o "Chapter20.md" code  "Pragmatic Starter Kit CLI Conclusion: Building a Pragmatic Future"
fgn -m2 -a -i blackboard.md -e "Chapter01.md" -o "Chapter02.md" code  " The Pragmatic Philosophy"
fgn -m2 -a -i blackboard.md -e "Chapter02.md" -o "Chapter03.md" code  "Pragmatic Starter Kit CLI DDD and code  Generation"
fgn -m2 -a -i blackboard.md -e "Chapter03.md" -o "Chapter04.md" code  "Pragmatic Starter Kit CLI Automated Testing with Pytest"
fgn -m2 -a -i blackboard.md -e "Chapter04.md" -o "Chapter05.md" code  "Pragmatic Starter Kit CLI Docker Compose for Environment Management"
fgn -m2 -a -i blackboard.md -e "Chapter05.md" -o "Chapter06.md" code  "Pragmatic Starter Kit CLI Continuous Integration with Git Actions"
fgn -m2 -a -i blackboard.md -e "Chapter06.md" -o "Chapter07.md" code  "Pragmatic Starter Kit CLI Refinement and Iteration in code  Generation"
fgn -m2 -a -i blackboard.md -e "Chapter07.md" -o "Chapter08.md" code  "Pragmatic Starter Kit CLI Version Control Strategies"
fgn -m2 -a -i blackboard.md -e "Chapter08.md" -o "Chapter09.md" code  "Pragmatic Starter Kit CLI Building the Pragmatic Starter Kit"
fgn -m2 -a -i blackboard.md -e "Chapter09.md" -o "Chapter10.md" code  "Pragmatic Starter Kit CLI Regression Testing and Full Automation"
fgn -m2 -a -i blackboard.md -e "Chapter10.md" -o "Chapter11.md" code  "Pragmatic Starter Kit CLI Monitoring and Performance Optimization"
fgn -m2 -a -i blackboard.md -e "Chapter11.md" -o "Chapter12.md" code  "Pragmatic Starter Kit CLI Documentation and Community Engagement"
fgn -m2 -a -i blackboard.md -e "Chapter12.md" -o "Chapter13.md" code  "Pragmatic Starter Kit CLI Security and Compliance"
fgn -m2 -a -i blackboard.md -e "Chapter13.md" -o "Chapter14.md" code  "Pragmatic Starter Kit CLI Deployment and Scalability"
fgn -m2 -a -i blackboard.md -e "Chapter14.md" -o "Chapter15.md" code  "Pragmatic Starter Kit CLI Debugging and Troubleshooting"
fgn -m2 -a -i blackboard.md -e "Chapter15.md" -o "Chapter16.md" code  "Pragmatic Starter Kit CLI Customizing the Pragmatic Starter Kit"
fgn -m2 -a -i blackboard.md -e "Chapter16.md" -o "Chapter17.md" code  "Pragmatic Starter Kit CLI Real-world Case Studies"
fgn -m2 -a -i blackboard.md -e "Chapter17.md" -o "Chapter18.md" code  "Pragmatic Starter Kit CLI Future Directions and Evolution"
fgn -m2 -a -i blackboard.md -e "Chapter18.md" -o "Chapter19.md" code  "Pragmatic Starter Kit CLI Contributing to the Project"
fgn -m2 -a -i blackboard.md -e "Chapter19.md" -o "Chapter20.md" code  "Pragmatic Starter Kit CLI Conclusion: Building a Pragmatic Future"
fgn -m2 -a -i blackboard.md -e "Chapter01.md" -o "Chapter02.md" code  " The Pragmatic Philosophy"
fgn -m2 -a -i blackboard.md -e "Chapter02.md" -o "Chapter03.md" code  "Pragmatic Starter Kit CLI DDD and code  Generation"
fgn -m2 -a -i blackboard.md -e "Chapter03.md" -o "Chapter04.md" code  "Pragmatic Starter Kit CLI Automated Testing with Pytest"
fgn -m2 -a -i blackboard.md -e "Chapter04.md" -o "Chapter05.md" code  "Pragmatic Starter Kit CLI Docker Compose for Environment Management"
fgn -m2 -a -i blackboard.md -e "Chapter05.md" -o "Chapter06.md" code  "Pragmatic Starter Kit CLI Continuous Integration with Git Actions"
fgn -m2 -a -i blackboard.md -e "Chapter06.md" -o "Chapter07.md" code  "Pragmatic Starter Kit CLI Refinement and Iteration in code  Generation"
fgn -m2 -a -i blackboard.md -e "Chapter07.md" -o "Chapter08.md" code  "Pragmatic Starter Kit CLI Version Control Strategies"
fgn -m2 -a -i blackboard.md -e "Chapter08.md" -o "Chapter09.md" code  "Pragmatic Starter Kit CLI Building the Pragmatic Starter Kit"
fgn -m2 -a -i blackboard.md -e "Chapter09.md" -o "Chapter10.md" code  "Pragmatic Starter Kit CLI Regression Testing and Full Automation"
fgn -m2 -a -i blackboard.md -e "Chapter10.md" -o "Chapter11.md" code  "Pragmatic Starter Kit CLI Monitoring and Performance Optimization"
fgn -m2 -a -i blackboard.md -e "Chapter11.md" -o "Chapter12.md" code  "Pragmatic Starter Kit CLI Documentation and Community Engagement"
fgn -m2 -a -i blackboard.md -e "Chapter12.md" -o "Chapter13.md" code  "Pragmatic Starter Kit CLI Security and Compliance"
fgn -m2 -a -i blackboard.md -e "Chapter13.md" -o "Chapter14.md" code  "Pragmatic Starter Kit CLI Deployment and Scalability"
fgn -m2 -a -i blackboard.md -e "Chapter14.md" -o "Chapter15.md" code  "Pragmatic Starter Kit CLI Debugging and Troubleshooting"
fgn -m2 -a -i blackboard.md -e "Chapter15.md" -o "Chapter16.md" code  "Pragmatic Starter Kit CLI Customizing the Pragmatic Starter Kit"
fgn -m2 -a -i blackboard.md -e "Chapter16.md" -o "Chapter17.md" code  "Pragmatic Starter Kit CLI Real-world Case Studies"
fgn -m2 -a -i blackboard.md -e "Chapter17.md" -o "Chapter18.md" code  "Pragmatic Starter Kit CLI Future Directions and Evolution"
fgn -m2 -a -i blackboard.md -e "Chapter18.md" -o "Chapter19.md" code  "Pragmatic Starter Kit CLI Contributing to the Project"
fgn -m2 -a -i blackboard.md -e "Chapter19.md" -o "Chapter20.md" code  "Pragmatic Starter Kit CLI Conclusion: Building a Pragmatic Future"