# fgn/commands/lts/lts_config.yml
defaults:
  template: lts_template.txt
  example: lts_example.txt
  system_prompt: lts_system_prompt.txt
  history_path: lts_history.txt
  model: gpt-3.5-turbo
  auto_clear: false
  verbose: false
  auto_summarize: int = 4