fgn -e blackboard.md -m2 -o "prepare_environment.md" plan "Preparing the Environment for Auto GPT System Implementation"
fgn -e blackboard.md -m2 -i "prepare_environment.md" -o "system_design.md" plan "Designing the Auto GPT System"
fgn -e blackboard.md -m2 -i "system_design.md" -o "core_implementation.md" howto "How to Implement the Core Modules of Auto GPT System"
fgn -e blackboard.md -m2 -i "core_implementation.md" -o "workflow_automation.md" guide "Setting Up Workflow and Automation for Auto GPT System"
fgn -e blackboard.md -m2 -i "workflow_automation.md" -o "file_management.md" nano "Managing Files in Auto GPT System"
fgn -e blackboard.md -m2 -i "file_management.md" -o "code_generation.md" blog "Code Generation in Auto GPT System"
fgn -e blackboard.md -m2 -i "code_generation.md" -o "testing.md" howto "Testing and Monitoring the Auto GPT System"
fgn -e blackboard.md -m2 -i "testing.md" -o "review.md" plan "Review Checklist for Auto GPT System"
fgn -e blackboard.md -m2 -i "review.md" -o "deployment_monitoring.md" guide "Deploying and Monitoring the Auto GPT System"
fgn -e blackboard.md -m2 -i "deployment_monitoring.md" -o "performance_optimization.md" howto "Optimizing the Performance of Auto GPT System"
fgn -e blackboard.md -m2 -i "performance_optimization.md" -o "contest_entry.md" plan "Contest Entry Plan using Auto GPT System"
fgn -e blackboard.md -m2 -i "contest_entry.md" -o "finalization.md" howto "Finalization and Documentation of Auto GPT System"